---
title: 'Cyclistic Bike-Share Case Study'
author: "Allan Lam"
date: "2025-09-12"
output:
  pdf_document: default
  html_document: default
---
## Setting up my environment 
Notes: setting up my R environment by loading the relevant packages
```{r loading packages}
library(tidyverse)
library(ggplot2)
library(scales)
```

## Processing csv files
```{r processing csv files}
setwd("~/Desktop/Divvy_Trips")

Q1_2019 = read.csv("/Users/allanlam/Desktop/Divvy_Trips/Divvy_Trips_2019_Q1.csv") %>% mutate(year = "2019")
glimpse(Q1_2019) 
Q1_2020 = read.csv("/Users/allanlam/Desktop/Divvy_Trips/Divvy_Trips_2020_Q1.csv") %>% mutate(year = "2020")
glimpse(Q1_2020) 

#change to numeric 
Q1_2019$ride_length = as.numeric(Q1_2019$ride_length) 
Q1_2020$ride_length = as.numeric(Q1_2020$ride_length) 
#check for NAs
any((is.na(Q1_2019$ride_length))) 
any((is.na(Q1_2020$ride_length)))
Q1_2020 = na.omit(Q1_2020) #Trips with 0 seconds, so omit for conciseness  

#edit consistent naming for membership type
Q1_2020 = Q1_2020 %>%
  mutate(usertype = case_when(
    member_casual == "casual" ~ "Customer",
    member_casual == "member" ~ "Subscriber"
  ))
#check for NAs
any(is.na(Q1_2020$member_casual))

#rename column names for consistency
Q1_2020_renamed = Q1_2020 %>% 
  rename (
    trip_id = ride_id,
    start_time = started_at, 
    end_time = ended_at,
    from_station_name = start_station_name,
    to_station_name = end_station_name
  )

#select columns of interest for merging 
Q1_2019_trimmed = Q1_2019 %>% select(trip_id, start_time, end_time, from_station_name, to_station_name, usertype,  ride_length, day_of_week, year)
Q1_2019_trimmed$trip_id = as.character(Q1_2019_trimmed$trip_id) #change to character for merging 
Q1_2020_trimmed = Q1_2020_renamed %>% select(trip_id, start_time, end_time, from_station_name, to_station_name, usertype, ride_length, day_of_week, year)
Q1_agg_trimmed = full_join(Q1_2019_trimmed, Q1_2020_trimmed)

#label day_of_week into weekdays
Q1_agg_trimmed = Q1_agg_trimmed %>%  mutate (day_of_week = 
                              case_when(
                             day_of_week == "1" ~"Sunday",
                             day_of_week == "2" ~"Monday",
                             day_of_week == "3" ~"Tuesday",
                             day_of_week == "4" ~"Wednesday",
                             day_of_week == "5" ~"Thursday",
                             day_of_week == "6" ~"Friday",
                             day_of_week == "7" ~"Saturday"))
Q1_agg_trimmed$day_of_week = factor(
  Q1_agg_trimmed$day_of_week,
  levels = c("Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday")
)

#clean data format for ride_length into minutes and seconds
Q1_agg_trimmed = Q1_agg_trimmed %>%
  mutate(ride_length_sec = round(ride_length * 24 * 60 * 60, 2),
         ride_length_min = round(ride_length * 24 * 60, 2),
         total_ride_trips =  n()
         )
glimpse(Q1_agg_trimmed)
#check for NAs
any(is.na(Q1_agg_trimmed$ride_length_sec))
any(is.na(Q1_agg_trimmed$ride_length_min))

# write_csv(Q1_agg_trimmed, "Q1_agg_trimmed.csv")
```

## Data analysis 
```{r data analysis}
# Calculate the descriptive stats of the data (by user type)
Q1_summary = Q1_agg_trimmed %>% 
  group_by(usertype) %>% 
  summarize(group_trips = n(),
            mean_ride_length_sec = mean(ride_length_sec, na.rm = TRUE),
            max_ride_length_sec = max(ride_length_sec, na.rm = TRUE),
            min_ride_length_sec = min(ride_length_sec, na.rm = TRUE),
            sd_ride_length_sec = sd(ride_length_sec, na.rm = TRUE),
            
            mean_ride_length_min = mean(ride_length_min, na.rm = TRUE),
            max_ride_length_min = max(ride_length_min, na.rm = TRUE),
            min_ride_length_min = min(ride_length_min, na.rm = TRUE),
            sd_ride_length_min = sd(ride_length_min, na.rm = TRUE),
            # find the most frequent week of usage 
            mode_day_of_week = names(sort(table(day_of_week), decreasing = TRUE))[1])

# Bar plot: Mean ride length by user type
ggplot(data = Q1_summary, aes(x= usertype, y= mean_ride_length_min, fill = usertype)) + 
  geom_col() + 
  geom_text(aes(label = round(mean_ride_length_min,2)), vjust = -0.5) +
  labs(title = "Mean Ride Length by User Type", y = "Mean Ride Length (minutes)", x = "User Type") +
  ylim(0,85) +
  theme_light()

# Bar plot: Total trips by user type
ggplot(data = Q1_summary, aes(x= usertype, y= group_trips, fill = usertype)) + 
  geom_col() + 
  geom_text(aes(label = scales::comma(group_trips)), vjust = -0.2) +
  labs(title = "Total Trips by User Type", y = "Total Trips", x = "User Type") +
  scale_y_continuous(labels = comma) +
  theme_light() 

# Calculate the descriptive stats of the data (by user type and day of week)
Q1_summary_by_days = Q1_agg_trimmed %>% 
  group_by(usertype, day_of_week) %>% 
  summarize(group_trips = n(),
            mean_ride_length_sec = mean(ride_length_sec, na.rm = TRUE),
            max_ride_length_sec = max(ride_length_sec, na.rm = TRUE),
            min_ride_length_sec = min(ride_length_sec, na.rm = TRUE),
            sd_ride_length_sec = sd(ride_length_sec, na.rm = TRUE),
            
            mean_ride_length_min = mean(ride_length_min, na.rm = TRUE),
            max_ride_length_min = max(ride_length_min, na.rm = TRUE),
            min_ride_length_min = min(ride_length_min, na.rm = TRUE),
            sd_ride_length_min = sd(ride_length_min, na.rm = TRUE))

# Bar plot: Mean Ride Length by User Type, Faceted by Day
ggplot(data = Q1_summary_by_days, aes(x= usertype, y= mean_ride_length_min, fill = usertype)) + 
  geom_col() +
  geom_text(aes(label = round(mean_ride_length_min,2)), vjust = -0.2) +
  facet_wrap(~ fct_relevel(day_of_week,
                           "Monday", "Tuesday", "Wednesday", 
                           "Thursday", "Friday", "Saturday", "Sunday"), axes = "all") +
  labs(title = "Mean Ride Length by User Type, Separated by Day", y = "Mean Ride Length (minutes)", x = "User Type") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2)))+
  theme_light()

# Bar plot: Total Trips by User Type, Faceted by Day
ggplot(data = Q1_summary_by_days, aes(x= usertype, y= group_trips, fill = usertype)) + 
  geom_col() + 
  geom_text(aes(label = scales::comma(group_trips)), vjust = -0.1) +
   facet_wrap(~ fct_relevel(day_of_week,
                           "Monday", "Tuesday", "Wednesday", 
                           "Thursday", "Friday", "Saturday", "Sunday"), axes = "all") +
  labs(title = "Total Trips by User Type, Separated by Day", y = "Mean Ride Length (minutes)", x = "User Type") +
  scale_y_continuous(labels = comma,expand = expansion(mult = c(0, 0.2)))+ 
  theme_light() 
```

## Statistical Modeling and Analysis 
```{r statistical modeling and analysis}
# Drop extreme outliers 
Q1_agg_trimmed = subset(Q1_agg_trimmed, ride_length_min > 0 & ride_length_min < 300)

# Generalized Linear Model with Gamma + log link (ride_length_min ~ usertype)
glm_ride = glm(ride_length_min ~ usertype, data = Q1_agg_trimmed,
                 family = Gamma(link = "log"))
summary(glm_ride)
glm_summary_ride = summary(glm_ride)
glm_coef_ride = coef(glm_ride)
coef_exp_ride = exp(glm_coef_ride) #exp transform
pvals_ride = glm_summary_ride$coefficients[, "Pr(>|t|)"]
customer_mean_ride = coef_exp_ride["(Intercept)"]
subscriber_ratio_ride = coef_exp_ride["usertypeSubscriber"]

# Print result sentence for glm
cat("Generalized Linear Model (Gamma with log link) predicting ride length:\n")
cat("Average ride length for Customers is about", round(customer_mean_ride, 2), "minutes.\n")
if (subscriber_ratio_ride < 1) {
  cat("Subscribers ride about", round(subscriber_ratio_ride, 2),
      "times as long as Customers (i.e., shorter).\n")
} else {
  cat("Subscribers ride about", round(subscriber_ratio_ride, 2),
      "times as long as Customers (i.e., longer).\n")
}

# APA-style p-value
if (pvals_ride["usertypeSubscriber"] < .001) {
  cat("This difference is statistically significant (p < .001).\n\n")
} else {
  cat("The difference is not statistically significant (p =",
      format.pval(pvals_ride["usertypeSubscriber"], digits = 3), ").\n\n")
}

# Generalized Linear Model with Gamma + log link (group_trips ~ usertype)
glm_trips = glm(group_trips ~ usertype, data = Q1_summary,
                 family = poisson(link = "log"))
summary(glm_trips)
glm_summary_trips = summary(glm_trips)
glm_coef_trips = coef(glm_trips)
coef_exp_trips = exp(glm_coef_trips) #exp transform
pvals_trips = glm_summary_trips$coefficients[, "Pr(>|z|)"]
customer_mean_trips = coef_exp_trips["(Intercept)"]
subscriber_ratio_trips = coef_exp_trips["usertypeSubscriber"]

# APA-style reporting
cat("Generalized Linear Model (Poisson with log link) predicting total trips:\n")
cat("Average number of trips for Customers is about", round(customer_mean_trips, 2), "trips.\n")

if (subscriber_ratio_trips < 1) {
  cat("Subscribers ride about", round(subscriber_ratio_trips, 2),
      "times total trips as Customers (i.e., fewer).\n")
} else {
  cat("Subscribers ride about", round(subscriber_ratio_trips, 2),
      "times total trips as Customers (i.e., more).\n")
}

# APA-style p-value
if (pvals_trips["usertypeSubscriber"] < .001) {
  cat("This difference is statistically significant (p < .001).\n\n")
} else {
  cat("The difference is not statistically significant (p =",
      format.pval(pvals_trips["usertypeSubscriber"], digits = 3), ").\n\n")
}

# Two ways ANOVA (ride_length_min ~ usertype*day_of_week)
ANOVA = aov(ride_length_min ~ usertype * day_of_week, data = Q1_agg_trimmed)
summary(ANOVA)[[1]]
anova_summary = summary(ANOVA)[[1]]
effects = rownames(anova_summary)[1:3]   # usertype, day_of_week, interaction

# Function to format APA-style sentence
format_APA = function(effect, table){
  df1 = table[effect, "Df"]
  df2 = table["Residuals", "Df"]
  Fval = table[effect, "F value"]
  pval = table[effect, "Pr(>F)"]
  
  # p-value APA
  if (pval < .001) {
    p_txt = "p < .001"
  } else {
    p_txt = paste0("p = ", format.pval(pval, digits = 3, eps = .001))
  }

  # Full APA sentence
  paste0("There was a significant effect of ", effect,
         ", F(", df1, ", ", df2, ") = ",
         round(Fval, 2), ", ", p_txt, ".")
}

# Apply function to each effect
apa_results = sapply(effects, format_APA, table = anova_summary)

# Print sentences
cat("ANOVA reveals several main effects on average ride length \n")
cat(paste(apa_results, collapse = "\n"))

# Histogram: Distribution of Ride Length by User Type
ggplot(Q1_agg_trimmed, aes(x = ride_length_min, fill = usertype)) +
  geom_histogram(binwidth = 2, alpha = 0.6, position = "identity") +
  xlim(0, 100) +   # trim extreme rides
  labs(title = "Distribution of Ride Length by User Type",
       x = "Ride Length (minutes)", y = "Count")+ 
  theme_light() 

# Pie chart: Proportion of Total Trips by User Type
Q1_summary %>%
  mutate(prop = group_trips / sum(group_trips)) %>%
  ggplot(aes(x = "", y = prop, fill = usertype)) +
  geom_bar(stat = "identity", width = 0.5) +
  geom_text(aes(label = round(prop,2)), hjust = -0.1, size = 5) +
  coord_polar(theta = "y") +
  labs(title = "Proportion of Total Trips by User Type") +
  theme_void()

# Boxplot: Ride Length by User Type and Day of Week
ggplot(Q1_agg_trimmed, aes(x = day_of_week, y = ride_length_min, fill = usertype)) +
  geom_boxplot(outlier.shape = NA) +                                   
  coord_cartesian(ylim = c(0, 50)) +                                   
  labs(title = "Ride Length by User Type and Day of Week",             
       x = "Day of Week",                                              
       y = "Ride Length (minutes)") +                                   
  theme_light()                                                        
```

